# Generated by Django 5.2.4 on 2025-07-30 10:31

import mevzuat.documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mevzuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('document', models.FileField(upload_to=mevzuat.documents.models.document_upload_to)),
                ('name', models.CharField(max_length=600)),
                ('mevzuat_tur', models.PositiveSmallIntegerField(choices=[(1, 'Kanun')])),
                ('mevzuat_no', models.CharField(max_length=16, unique=True)),
                ('mevzuat_tertib', models.PositiveSmallIntegerField()),
                ('kabul_tarih', models.DateField(blank=True, null=True)),
                ('resmi_gazete_tarihi', models.DateField(blank=True, null=True)),
                ('resmi_gazete_sayisi', models.CharField(blank=True, max_length=16, null=True)),
                ('nitelik', models.CharField(blank=True, max_length=120, null=True)),
                ('mukerrer', models.BooleanField(default=False, help_text='Whether this is a duplicate issue.')),
                ('tuzuk_mevzuat_tur', models.PositiveSmallIntegerField(default=0)),
                ('has_old_law', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
