# Generated by Django 5.2.4 on 2025-07-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mevzuat',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mevzuat',
            name='mevzuat_no',
            field=models.CharField(max_length=16),
        ),
        migrations.AddConstraint(
            model_name='mevzuat',
            constraint=models.UniqueConstraint(fields=('mevzuat_tur', 'mevzuat_tertib', 'mevzuat_no'), name='uniq_mevzuat_tur_tertip_no'),
        ),
    ]
