# Generated by Django 5.2.4 on 2025-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_mevzuat_updated_at_alter_mevzuat_mevzuat_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mevzuat',
            name='mevzuat_tur',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kanun'), (19, 'Cumhurbaşkanlığı Kararnamesi'), (21, 'Cumhurbaşkanlığı Yönetmeliği'), (20, 'Cumhurbaşkanı Kararı'), (22, 'Cumhurbaşkanlığı Genelgesi'), (4, 'KHK'), (2, 'Tüzük'), (17, 'İç Tüzük'), (6, 'Tüzük (?)'), (7, 'Yönetmelik'), (8, 'Yönetmelik (Üniversite)'), (9, 'Tebliğ')]),
        ),
    ]
