# Generated by Django 5.2.4 on 2025-07-31 12:44

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_mevzuat_mevzuat_tur'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveConstraint(
            model_name='mevzuat',
            name='uniq_mevzuat_tur_tertip_no',
        ),
        migrations.AddField(
            model_name='mevzuat',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='mevzuat',
            name='oai_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='mevzuat',
            constraint=models.UniqueConstraint(fields=('mevzuat_tur', 'mevzuat_tertib', 'mevzuat_no', 'resmi_gazete_tarihi'), name='uniq_mevzuat_tur_tertip_no'),
        ),
    ]
