# Generated by Django 5.2.4 on 2025-08-01 19:13

import mevzuat.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_mevzuat_uniq_mevzuat_tur_tertip_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mevzuat',
            name='markdown',
            field=models.FileField(blank=True, null=True, upload_to=mevzuat.documents.models.document_upload_to),
        ),
        migrations.AlterField(
            model_name='mevzuat',
            name='mevzuat_tur',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kanun'), (19, 'Cumhurbaşkanlığı Kararnamesi'), (21, 'Cumhurbaşkanlığı Yönetmeliği'), (20, 'Cumhurbaşkanı Kararı'), (22, 'Cumhurbaşkanlığı Genelgesi'), (4, 'KHK'), (2, 'Tüzük'), (17, 'İç Tüzük'), (6, 'Tüzük (?)'), (7, 'Kurum Yönetmeliği'), (8, 'Kurum Yönetmeliği (Üniversite)'), (9, 'Tebliğ')]),
        ),
    ]
