# Generated by Django 5.2.4 on 2025-08-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_mevzuat_markdown_alter_mevzuat_mevzuat_tur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mevzuat',
            old_name='oai_id',
            new_name='oai_file_id',
        ),
    ]
