# Generated by Django 5.2.4 on 2025-08-03 12:03

import mevzuat.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_rename_oai_id_mevzuat_oai_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mevzuat',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=mevzuat.documents.models.document_upload_to),
        ),
    ]
