# Generated by Django 5.2.4 on 2025-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_mevzuat_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mevzuat',
            name='mevzuat_tur',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kanun'), (4, 'KHK'), (19, 'Cumhurbaşkanlığı Kararnamesi'), (20, 'Cumhurbaşkanı Kararı'), (21, 'Cumhurbaşkanlığı Yönetmeliği'), (22, 'Cumhurbaşkanlığı Genelgesi')], db_index=True),
        ),
    ]
