# Generated by Django 5.2.4 on 2025-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documenttype_vectorstore_mevzuat_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorstore',
            name='oai_vs_id',
            field=models.CharField(default='*', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
