# Generated by Django 5.2.4 on 2025-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_vectorstore_oai_vs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
