# Generated by Django 5.2.4 on 2025-08-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documenttype_active_alter_documenttype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='active',
        ),
    ]
