# Generated by Django 5.2.4 on 2025-08-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_documenttype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mevzuat',
            name='title',
            field=models.CharField(default='*', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mevzuat',
            name='mevzuat_tur',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kanun'), (4, 'KHK'), (19, 'Cumhurbaşkanlığı Kararnamesi'), (20, 'Cumhurbaşkanı Kararı'), (21, 'Cumhurbaşkanlığı Yönetmeliği'), (22, 'Cumhurbaşkanlığı Genelgesi'), (2, 'Tüzük'), (17, 'İç Tüzük'), (6, 'Tüzük (x)'), (7, 'Kurum Yönetmeliği'), (8, 'Üniversite Yönetmeliği'), (9, 'Tebliğ'), (0, 'Eski kanun')], db_index=True),
        ),
        migrations.AlterField(
            model_name='mevzuat',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype'),
        ),
    ]
