# Generated by Django 5.2.4 on 2025-08-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_mevzuat_title_alter_mevzuat_mevzuat_tur_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mevzuat',
            name='uniq_mevzuat_tur_tertip_no',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='mevzuat_tur',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='name',
        ),
    ]
