# Generated by Django 5.2.4 on 2025-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_remove_mevzuat_uniq_mevzuat_tur_tertip_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='original_document_url_pattern',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='fetcher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
