# Generated by Django 5.2.4 on 2025-08-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_documenttype_original_document_url_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mevzuat',
            name='has_old_law',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='kabul_tarih',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='mevzuat_no',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='mevzuat_tertib',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='mukerrer',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='nitelik',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='resmi_gazete_sayisi',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='resmi_gazete_tarihi',
        ),
        migrations.RemoveField(
            model_name='mevzuat',
            name='tuzuk_mevzuat_tur',
        ),
    ]
