# Generated by Django 5.2.4 on 2025-08-06 19:56

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_mevzuat_has_old_law_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mevzuat',
            new_name='Document',
        ),
        migrations.AlterModelTable(
            name='document',
            table='documents_mevzuat',
        ),
    ]
