# Generated by Django 5.2.4 on 2025-08-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_rename_mevzuat_document_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
