# Generated by Django 5.2.4 on 2025-08-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='default_vector_store',
            new_name='vector_store',
        ),
    ]
