# Generated by Django 5.2.4 on 2025-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_rename_default_vector_store_documenttype_vector_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
