# Generated by Django 5.2.4 on 2025-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_documenttype_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
