# Generated by Django 5.2.4 on 2025-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
