# Generated by Django 5.2.8 on 2026-01-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='markdown_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=20, null=True),
        ),
    ]
