# Generated by Django 5.2.8 on 2026-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_document_summary_alter_document_markdown_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
