# Generated by Django 5.2.8 on 2026-01-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_add_translation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='vector_store',
        ),
        migrations.DeleteModel(
            name='VectorStore',
        ),
    ]
