# Generated by Django 5.2.8 on 2026-01-02 15:45

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_remove_vector_store'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='topiccontent_embedding_hnsw', opclasses=['vector_l2_ops']),
        ),
    ]
