# Generated by Django 5.2.8 on 2026-01-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_document_topiccontent_embedding_hnsw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='oai_file_id',
        ),
    ]
