# Generated by Django 5.2.8 on 2026-01-03 06:10

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_flaggeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('normalized_query', models.TextField(unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
