# Generated by Django 5.2.8 on 2026-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0033_searchqueryembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
