# Generated by Django 5.2.8 on 2026-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0034_document_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="document",
            name="keywords_en",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
